Upgrade from django_watson 1.1.8 to 1.2.0
Django_watson 1.2 introduced a breaking change in import style, in order
to be compatible with Django 1.9.  See the changelog linked from
https://groups.google.com/forum/#!topic/django-watson/mY3_78IdHbw for
more information.  Update our import of watson to be in the new
(correct) style.

We had been getting the error

   AttributeError: 'module' object has no attribute 'admin'

for the line `search_engine = watson.admin.admin_search_engine` in our
admin.py when running any `python manage.py` command.